[package]
name = "cli-utils"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.4", features = ["derive"] }
regex = { version = "1.11.1"}
colored = { version = "3.0.0"}
rayon = { version = "1.8"}